# Generated by Django 3.1.7 on 2021-03-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Фото курса')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена за курс')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Продолжительность мес.')),
                ('course_description', models.TextField(verbose_name='Продолжительность курса')),
                ('diplome', models.BooleanField(verbose_name='Наличие диплома')),
                ('course_programm', models.TextField(verbose_name='Программа курса')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Школа')),
                ('logo', models.ImageField(upload_to='school', verbose_name='Логотип школы')),
                ('specialization', models.CharField(choices=[('programming', 'Программтрование'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('analytics', 'Аналитика'), ('media', 'Фото, видео, аудио'), ('business', 'Бизнес')], max_length=50, verbose_name='Спциализация')),
                ('desciption', models.TextField(verbose_name='Описание школы')),
                ('rating', models.IntegerField(default=5, verbose_name='Рейтинг')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('courses', models.ManyToManyField(to='courses.Course', verbose_name='Список курсов')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='which_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.school', verbose_name='Школа'),
        ),
    ]
