# Generated by Django 3.1.7 on 2021-03-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='specialization',
            field=models.CharField(choices=[('programming', 'Программирование'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('analytics', 'Аналитика'), ('media', 'Фото, видео, аудио'), ('business', 'Бизнес')], max_length=50, verbose_name='Спциализация'),
        ),
    ]
