# Generated by Django 3.1.7 on 2021-03-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210301_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='specialization',
        ),
        migrations.CreateModel(
            name='Specialiazation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название специализации')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('courses', models.ManyToManyField(to='courses.Course', verbose_name='Курсы в специализации')),
                ('schools', models.ManyToManyField(to='courses.School', verbose_name='Школы в специализации')),
            ],
            options={
                'verbose_name': 'Нап',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ManyToManyField(to='courses.Specialiazation', verbose_name='Специализация курса'),
        ),
        migrations.AddField(
            model_name='school',
            name='specialization',
            field=models.ManyToManyField(to='courses.Specialiazation', verbose_name='Специализация школы'),
        ),
    ]
