# Generated by Django 3.1.7 on 2021-03-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210301_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialiazation',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, verbose_name='Продолжительность курса'),
        ),
        migrations.AlterField(
            model_name='school',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Course', verbose_name='Список курсов'),
        ),
        migrations.AlterField(
            model_name='school',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='courses.Specialiazation', verbose_name='Специализация школы'),
        ),
        migrations.AlterField(
            model_name='specialiazation',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Course', verbose_name='Курсы в специализации'),
        ),
        migrations.AlterField(
            model_name='specialiazation',
            name='schools',
            field=models.ManyToManyField(blank=True, to='courses.School', verbose_name='Школы в специализации'),
        ),
    ]
