# Generated by Django 3.1.7 on 2021-03-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210301_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialiazation',
            new_name='Specialization',
        ),
        migrations.RemoveField(
            model_name='course',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='school',
            name='specialization',
        ),
        migrations.AddField(
            model_name='course',
            name='school_spec',
            field=models.ManyToManyField(to='courses.Specialization', verbose_name='Специализация курса'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_spec',
            field=models.ManyToManyField(blank=True, to='courses.Specialization', verbose_name='Специализация школы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, verbose_name='Описание курса'),
        ),
    ]
