# Generated by Django 3.1.7 on 2021-03-04 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_auto_20210301_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='userpics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.userprofile', verbose_name='Кто написал')),
                ('school_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.school', verbose_name='какая школа')),
            ],
            options={
                'verbose_name': 'Отзыв о школе',
                'verbose_name_plural': 'Отзывы о школе',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('course_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='какой курс')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.userprofile', verbose_name='Кто написал')),
            ],
            options={
                'verbose_name': 'Отзыв о курсе',
                'verbose_name_plural': 'Отзывы о курсе',
            },
        ),
    ]
