# Generated by Django 3.1.7 on 2021-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210305_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг курса'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='comment',
            field=models.CharField(max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='school',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='schoolreview',
            name='comment',
            field=models.CharField(max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='schoolreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг'),
        ),
    ]
